//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormSVJava.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceReference1.webservice")]
    public interface webservice {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://ws/)
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice/tongRequest", ReplyAction="http://ws/webservice/tongResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        FormSVJava.ServiceReference1.tongResponse tong(FormSVJava.ServiceReference1.tongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice/tongRequest", ReplyAction="http://ws/webservice/tongResponse")]
        System.Threading.Tasks.Task<FormSVJava.ServiceReference1.tongResponse> tongAsync(FormSVJava.ServiceReference1.tongRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice/helloRequest", ReplyAction="http://ws/webservice/helloResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        FormSVJava.ServiceReference1.helloResponse hello(FormSVJava.ServiceReference1.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice/helloRequest", ReplyAction="http://ws/webservice/helloResponse")]
        System.Threading.Tasks.Task<FormSVJava.ServiceReference1.helloResponse> helloAsync(FormSVJava.ServiceReference1.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tong", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class tongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public tongRequest() {
        }
        
        public tongRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tongResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class tongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public tongResponse() {
        }
        
        public tongResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://ws/", Order=0)]
        public FormSVJava.ServiceReference1.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(FormSVJava.ServiceReference1.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://ws/", Order=0)]
        public FormSVJava.ServiceReference1.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(FormSVJava.ServiceReference1.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webserviceChannel : FormSVJava.ServiceReference1.webservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webserviceClient : System.ServiceModel.ClientBase<FormSVJava.ServiceReference1.webservice>, FormSVJava.ServiceReference1.webservice {
        
        public webserviceClient() {
        }
        
        public webserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormSVJava.ServiceReference1.tongResponse FormSVJava.ServiceReference1.webservice.tong(FormSVJava.ServiceReference1.tongRequest request) {
            return base.Channel.tong(request);
        }
        
        public int tong(int arg0, int arg1) {
            FormSVJava.ServiceReference1.tongRequest inValue = new FormSVJava.ServiceReference1.tongRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            FormSVJava.ServiceReference1.tongResponse retVal = ((FormSVJava.ServiceReference1.webservice)(this)).tong(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormSVJava.ServiceReference1.tongResponse> FormSVJava.ServiceReference1.webservice.tongAsync(FormSVJava.ServiceReference1.tongRequest request) {
            return base.Channel.tongAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormSVJava.ServiceReference1.tongResponse> tongAsync(int arg0, int arg1) {
            FormSVJava.ServiceReference1.tongRequest inValue = new FormSVJava.ServiceReference1.tongRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((FormSVJava.ServiceReference1.webservice)(this)).tongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormSVJava.ServiceReference1.helloResponse FormSVJava.ServiceReference1.webservice.hello(FormSVJava.ServiceReference1.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            FormSVJava.ServiceReference1.helloRequest inValue = new FormSVJava.ServiceReference1.helloRequest();
            inValue.Body = new FormSVJava.ServiceReference1.helloRequestBody();
            inValue.Body.name = name;
            FormSVJava.ServiceReference1.helloResponse retVal = ((FormSVJava.ServiceReference1.webservice)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormSVJava.ServiceReference1.helloResponse> FormSVJava.ServiceReference1.webservice.helloAsync(FormSVJava.ServiceReference1.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormSVJava.ServiceReference1.helloResponse> helloAsync(string name) {
            FormSVJava.ServiceReference1.helloRequest inValue = new FormSVJava.ServiceReference1.helloRequest();
            inValue.Body = new FormSVJava.ServiceReference1.helloRequestBody();
            inValue.Body.name = name;
            return ((FormSVJava.ServiceReference1.webservice)(this)).helloAsync(inValue);
        }
    }
}
