//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormSVJava.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        FormSVJava.ServiceReference2.HelloWorldResponse HelloWorld(FormSVJava.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<FormSVJava.ServiceReference2.HelloWorldResponse> HelloWorldAsync(FormSVJava.ServiceReference2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cong", ReplyAction="*")]
        int cong(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cong", ReplyAction="*")]
        System.Threading.Tasks.Task<int> congAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tru", ReplyAction="*")]
        int tru(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/tru", ReplyAction="*")]
        System.Threading.Tasks.Task<int> truAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nhan", ReplyAction="*")]
        int nhan(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/nhan", ReplyAction="*")]
        System.Threading.Tasks.Task<int> nhanAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chia", ReplyAction="*")]
        float chia(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chia", ReplyAction="*")]
        System.Threading.Tasks.Task<float> chiaAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public FormSVJava.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(FormSVJava.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormSVJava.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(FormSVJava.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : FormSVJava.ServiceReference2.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<FormSVJava.ServiceReference2.ServiceSoap>, FormSVJava.ServiceReference2.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormSVJava.ServiceReference2.HelloWorldResponse FormSVJava.ServiceReference2.ServiceSoap.HelloWorld(FormSVJava.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            FormSVJava.ServiceReference2.HelloWorldRequest inValue = new FormSVJava.ServiceReference2.HelloWorldRequest();
            inValue.Body = new FormSVJava.ServiceReference2.HelloWorldRequestBody();
            FormSVJava.ServiceReference2.HelloWorldResponse retVal = ((FormSVJava.ServiceReference2.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormSVJava.ServiceReference2.HelloWorldResponse> FormSVJava.ServiceReference2.ServiceSoap.HelloWorldAsync(FormSVJava.ServiceReference2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormSVJava.ServiceReference2.HelloWorldResponse> HelloWorldAsync() {
            FormSVJava.ServiceReference2.HelloWorldRequest inValue = new FormSVJava.ServiceReference2.HelloWorldRequest();
            inValue.Body = new FormSVJava.ServiceReference2.HelloWorldRequestBody();
            return ((FormSVJava.ServiceReference2.ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int cong(int a, int b) {
            return base.Channel.cong(a, b);
        }
        
        public System.Threading.Tasks.Task<int> congAsync(int a, int b) {
            return base.Channel.congAsync(a, b);
        }
        
        public int tru(int a, int b) {
            return base.Channel.tru(a, b);
        }
        
        public System.Threading.Tasks.Task<int> truAsync(int a, int b) {
            return base.Channel.truAsync(a, b);
        }
        
        public int nhan(int a, int b) {
            return base.Channel.nhan(a, b);
        }
        
        public System.Threading.Tasks.Task<int> nhanAsync(int a, int b) {
            return base.Channel.nhanAsync(a, b);
        }
        
        public float chia(int a, int b) {
            return base.Channel.chia(a, b);
        }
        
        public System.Threading.Tasks.Task<float> chiaAsync(int a, int b) {
            return base.Channel.chiaAsync(a, b);
        }
    }
}
