//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Client.WebService.HelloWorldResponse HelloWorld(Client.WebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name giai_pt_bac_1Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/giai_pt_bac_1", ReplyAction="*")]
        Client.WebService.giai_pt_bac_1Response giai_pt_bac_1(Client.WebService.giai_pt_bac_1Request request);
        
        // CODEGEN: Generating message contract since element name giai_pt_bac_2Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/giai_pt_bac_2", ReplyAction="*")]
        Client.WebService.giai_pt_bac_2Response giai_pt_bac_2(Client.WebService.giai_pt_bac_2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client.WebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Client.WebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.WebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Client.WebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class giai_pt_bac_1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="giai_pt_bac_1", Namespace="http://tempuri.org/", Order=0)]
        public Client.WebService.giai_pt_bac_1RequestBody Body;
        
        public giai_pt_bac_1Request() {
        }
        
        public giai_pt_bac_1Request(Client.WebService.giai_pt_bac_1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class giai_pt_bac_1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float b;
        
        public giai_pt_bac_1RequestBody() {
        }
        
        public giai_pt_bac_1RequestBody(float a, float b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class giai_pt_bac_1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="giai_pt_bac_1Response", Namespace="http://tempuri.org/", Order=0)]
        public Client.WebService.giai_pt_bac_1ResponseBody Body;
        
        public giai_pt_bac_1Response() {
        }
        
        public giai_pt_bac_1Response(Client.WebService.giai_pt_bac_1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class giai_pt_bac_1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string giai_pt_bac_1Result;
        
        public giai_pt_bac_1ResponseBody() {
        }
        
        public giai_pt_bac_1ResponseBody(string giai_pt_bac_1Result) {
            this.giai_pt_bac_1Result = giai_pt_bac_1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class giai_pt_bac_2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="giai_pt_bac_2", Namespace="http://tempuri.org/", Order=0)]
        public Client.WebService.giai_pt_bac_2RequestBody Body;
        
        public giai_pt_bac_2Request() {
        }
        
        public giai_pt_bac_2Request(Client.WebService.giai_pt_bac_2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class giai_pt_bac_2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float b;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float c;
        
        public giai_pt_bac_2RequestBody() {
        }
        
        public giai_pt_bac_2RequestBody(float a, float b, float c) {
            this.a = a;
            this.b = b;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class giai_pt_bac_2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="giai_pt_bac_2Response", Namespace="http://tempuri.org/", Order=0)]
        public Client.WebService.giai_pt_bac_2ResponseBody Body;
        
        public giai_pt_bac_2Response() {
        }
        
        public giai_pt_bac_2Response(Client.WebService.giai_pt_bac_2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class giai_pt_bac_2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string giai_pt_bac_2Result;
        
        public giai_pt_bac_2ResponseBody() {
        }
        
        public giai_pt_bac_2ResponseBody(string giai_pt_bac_2Result) {
            this.giai_pt_bac_2Result = giai_pt_bac_2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Client.WebService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Client.WebService.ServiceSoap>, Client.WebService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.WebService.HelloWorldResponse Client.WebService.ServiceSoap.HelloWorld(Client.WebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Client.WebService.HelloWorldRequest inValue = new Client.WebService.HelloWorldRequest();
            inValue.Body = new Client.WebService.HelloWorldRequestBody();
            Client.WebService.HelloWorldResponse retVal = ((Client.WebService.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.WebService.giai_pt_bac_1Response Client.WebService.ServiceSoap.giai_pt_bac_1(Client.WebService.giai_pt_bac_1Request request) {
            return base.Channel.giai_pt_bac_1(request);
        }
        
        public string giai_pt_bac_1(float a, float b) {
            Client.WebService.giai_pt_bac_1Request inValue = new Client.WebService.giai_pt_bac_1Request();
            inValue.Body = new Client.WebService.giai_pt_bac_1RequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            Client.WebService.giai_pt_bac_1Response retVal = ((Client.WebService.ServiceSoap)(this)).giai_pt_bac_1(inValue);
            return retVal.Body.giai_pt_bac_1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.WebService.giai_pt_bac_2Response Client.WebService.ServiceSoap.giai_pt_bac_2(Client.WebService.giai_pt_bac_2Request request) {
            return base.Channel.giai_pt_bac_2(request);
        }
        
        public string giai_pt_bac_2(float a, float b, float c) {
            Client.WebService.giai_pt_bac_2Request inValue = new Client.WebService.giai_pt_bac_2Request();
            inValue.Body = new Client.WebService.giai_pt_bac_2RequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            Client.WebService.giai_pt_bac_2Response retVal = ((Client.WebService.ServiceSoap)(this)).giai_pt_bac_2(inValue);
            return retVal.Body.giai_pt_bac_2Result;
        }
    }
}
