//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceMath {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMath.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/max", ReplyAction="*")]
        int max(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/min", ReplyAction="*")]
        int min(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sum", ReplyAction="*")]
        int sum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/average", ReplyAction="*")]
        double average(int sum, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/soLe", ReplyAction="*")]
        bool soLe(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/soChan", ReplyAction="*")]
        bool soChan(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/soNguyenTo", ReplyAction="*")]
        bool soNguyenTo(int a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Client.ServiceMath.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Client.ServiceMath.ServiceSoap>, Client.ServiceMath.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int max(int a, int b) {
            return base.Channel.max(a, b);
        }
        
        public int min(int a, int b) {
            return base.Channel.min(a, b);
        }
        
        public int sum(int a, int b) {
            return base.Channel.sum(a, b);
        }
        
        public double average(int sum, int number) {
            return base.Channel.average(sum, number);
        }
        
        public bool soLe(int a) {
            return base.Channel.soLe(a);
        }
        
        public bool soChan(int a) {
            return base.Channel.soChan(a);
        }
        
        public bool soNguyenTo(int a) {
            return base.Channel.soNguyenTo(a);
        }
    }
}
